# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CeliHack' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CeliHack

  pod "UXCam", "~> 2.5.8"

  #target 'CeliHackTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

end
